# olah data smn

In [1]:
import pandas as pd
smn = pd.read_excel('Data SMN 2021.xlsx', sheet_name='SMN_2')

In [2]:
smn

,Jenis Aset,Jenis Sarana,Tahun Pengadaan,Lokasi Penempatan,Sumber Pengadaan,Unit,Keterangan
0,1.1.1CC3001201,Lokomotif,2010-2011,PT INKA Madiun,Satker Pengembangan dan Peningkatan Sarana Per...,1.0,NaN
1,1.1.2CC3001202,Lokomotif,2010-2011,Workshop Balai Perawatan,Satker Pengembangan dan Peningkatan Sarana Per...,1.0,NaN
2,1.1.3CC3001203,Lokomotif,2010-2011,Depo Lokomotif Tanahabang,Satker Pengembangan dan Peningkatan Sarana Per...,1.0,NaN
3,1.1.4CC3001401,Lokomotif,2012-2013,Sumatera Utara,Satker Pengembangan dan Peningkatan Sarana Per...,1.0,NaN
4,1.1.5CC3001402,Lokomotif,2012-2013,Lampung,Satker Pengembangan dan Peningkatan Sarana Per...,1.0,NaN
...,...,...,...,...,...,...,...
158,4.7.2V2R510,Peralatan Khusus,2014,Workshop Balai Perawatan,Satker Prasarana Perkeretaapian,1.0,-Geismar
159,4.8.1FD2124,Peralatan Khusus,2012,Gudang Prasarana Jatibarang,Satker Prasarana Perkeretaapian,1.0,NaN
160,4.8.2FD2728,Peralatan Khusus,2014,Gudang Prasarana Parungpanjang,Satker Prasarana Perkeretaapian,1.0,NaN
161,4.8.3FD2713,Peralatan Khusus,2014,Gudang Prasarana Bangil,Satker Prasarana Perkeretaapian,1.0,NaN
162,4.8.4FD2724,Peralatan Khusus,2014,Gudang Prasarana Pekalongan,Satker Prasarana Perkeretaapian,1.0,NaN

In [3]:
import numpy as np

In [4]:
smn['No'] = np.arange(1,164)

In [5]:
smn = smn[['No', 'Jenis Aset','Jenis Sarana', 'Lokasi Penempatan']]

In [6]:
smn.head()

   No      Jenis Aset Jenis Sarana          Lokasi Penempatan
0   1  1.1.1CC3001201    Lokomotif             PT INKA Madiun
1   2  1.1.2CC3001202    Lokomotif   Workshop Balai Perawatan
2   3  1.1.3CC3001203    Lokomotif  Depo Lokomotif Tanahabang
3   4  1.1.4CC3001401    Lokomotif             Sumatera Utara
4   5  1.1.5CC3001402    Lokomotif                    Lampung

In [7]:
smn['Jenis Aset']= smn['Jenis Aset'].str.replace(' ','')

<ipython-input-7-9ea14b9e15b5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  smn['Jenis Aset']= smn['Jenis Aset'].str.replace(' ','')

In [8]:
smn.head()

   No      Jenis Aset Jenis Sarana          Lokasi Penempatan
0   1  1.1.1CC3001201    Lokomotif             PT INKA Madiun
1   2  1.1.2CC3001202    Lokomotif   Workshop Balai Perawatan
2   3  1.1.3CC3001203    Lokomotif  Depo Lokomotif Tanahabang
3   4  1.1.4CC3001401    Lokomotif             Sumatera Utara
4   5  1.1.5CC3001402    Lokomotif                    Lampung

In [9]:
smn['no_identitas'] = smn['Jenis Aset'].str[5:]

<ipython-input-9-21e2de826993>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  smn['no_identitas'] = smn['Jenis Aset'].str[5:]

In [10]:
smn['no_identitas2'] = smn['Jenis Aset'].str.extract(r"(?:.)\d+(\w+)", expand=False)

<ipython-input-10-4aa1a742b739>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  smn['no_identitas2'] = smn['Jenis Aset'].str.extract(r"(?:.)\d+(\w+)", expand=False)

In [11]:
smn.tail(50)

,No,Jenis Aset,Jenis Sarana,Lokasi Penempatan,no_identitas,no_identitas2
113,114,3.2.5SU01801,Peralatan Khusus,Workshop Balai Perawatan,SU01801,SU01801
114,115,3.3.1SI00901,Peralatan Khusus,Workshop Balai Perawatan,SI00901,SI00901
115,116,3.3.2SI00902,Peralatan Khusus,Workshop Balai Perawatan,SI00902,SI00902
116,117,3.3.3MP301003,Kereta,Workshop Balai Perawatan,MP301003,MP301003
117,118,3.3.4SI01101,Peralatan Khusus,Workshop Balai Perawatan,SI01101,SI01101
118,119,3.3.5SI01102,Peralatan Khusus,Workshop Balai Perawatan,SI01102,SI01102
119,120,3.3.6KI01601,Kereta,Workshop Balai Perawatan,KI01601,KI01601
120,121,3.4.1SN01501,Peralatan Khusus,Sulawesi Selatan,SN01501,SN01501
121,122,4.1.1SR31001,Peralatan Khusus,LRT Palembang,SR31001,SR31001
122,123,4.1.2SR31201,Peralatan Khusus,Depok,SR31201,SR31201
123,124,4.1.3SR31601,Peralatan Khusus,Sulawesi Selatan,SR31601,SR31601
124,125,4.2.1.1SC30501,Peralatan Khusus,Solo,.1SC30501,SC30501
125,126,4.2.1.2SN00801,Peralatan Khusus,Solo,.2SN00801,SN00801
126,127,4.2.1.3NNKW301001,Gerbong,Solo,.3NNKW301001,NNKW301001
127,128,4.2.2.1SC30502,Peralatan Khusus,Bandung,.1SC30502,SC30502
128,129,4.2.2.2SN00802,Peralatan Khusus,Bandung,.2SN00802,SN00802
129,130,4.2.2.3NNKW301002,Gerbong,Bandung,.3NNKW301002,NNKW301002
130,131,4.2.3.1SC31701,Peralatan Khusus,Sumatera Utara,.1SC31701,SC31701
131,132,4.2.3.2SN01701,Peralatan Khusus,Sumatera Utara,.2SN01701,SN01701
132,133,4.2.3.3GD401701,Gerbong,Sumatera Utara,.3GD401701,GD401701
133,134,4.3.1SK21501,Peralatan Khusus,BTP Wil. Jabar,SK21501,SK21501
134,135,4.3.2SK21502,Peralatan Khusus,BTP Wil. Jatim,SK21502,SK21502
135,136,4.3.3SK21503,Peralatan Khusus,BTP Wil. Jateng,SK21503,SK21503
136,137,4.3.4SK21504,Peralatan Khusus,BTP Wil. Sumut,SK21504,SK21504
137,138,4.3.5SK21505,Peralatan Khusus,BTP Wil. Sumsel,SK21505,SK21505
138,139,4.4.1SR31401,Peralatan Khusus,Depo Cipinang,SR31401,SR31401
139,140,4.4.2SR31402,Peralatan Khusus,Gudang Prasarana Jatibarang,SR31402,SR31402
140,141,4.4.3SR31403,Peralatan Khusus,Workshop Balai Perawatan,SR31403,SR31403
141,142,4.4.4SR31404,Peralatan Khusus,Gudang Prasarana Jatibarang,SR31404,SR31404
142,143,4.4.5SR31405,Peralatan Khusus,Sumatera Utara,SR31405,SR31405
143,144,4.4.6SR31406,Peralatan Khusus,Gudang Prasarana Jatibarang,SR31406,SR31406
144,145,4.4.7SR31407,Peralatan Khusus,Sumatera Utara,SR31407,SR31407
145,146,4.4.8SR31601,Peralatan Khusus,Sumatera Utara,SR31601,SR31601
146,147,4.4.9SR31602,Peralatan Khusus,Sulawesi Selatan,SR31602,SR31602
147,148,4.4.10SR31701,Peralatan Khusus,Sumatera Selatan,0SR31701,SR31701
148,149,4.4.11SR31702,Peralatan Khusus,Sumatera Selatan,1SR31702,SR31702
149,150,4.4.12SR31801,Peralatan Khusus,Sulawesi Selatan,2SR31801,SR31801
150,151,4.4.13SR31802,Peralatan Khusus,Sulawesi Selatan,3SR31802,SR31802
151,152,4.5.1SK31201,Peralatan Khusus,Workshop Balai Perawatan,SK31201,SK31201
152,153,4.5.2SK31401,Peralatan Khusus,Workshop Balai Perawatan,SK31401,SK31401
153,154,4.5.3SK31402,Peralatan Khusus,Gudang Prasarana Payakabung,SK31402,SK31402
154,155,4.5.4SK31302,Peralatan Khusus,Workshop Balai Perawatan,SK31302,SK31302
155,156,4.5.4SK31303,Peralatan Khusus,Workshop Balai Perawatan,SK31303,SK31303
156,157,4.6.1L26WAK41-00000,Peralatan Khusus,Workshop Balai Perawatan,L26WAK41-00000,L26WAK41
157,158,4.7.1V2R510,Peralatan Khusus,Sumatera Utara,V2R510,V2R510
158,159,4.7.2V2R510,Peralatan Khusus,Workshop Balai Perawatan,V2R510,V2R510
159,160,4.8.1FD2124,Peralatan Khusus,Gudang Prasarana Jatibarang,FD2124,FD2124
160,161,4.8.2FD2728,Peralatan Khusus,Gudang Prasarana Parungpanjang,FD2728,FD2728
161,162,4.8.3FD2713,Peralatan Khusus,Gudang Prasarana Bangil,FD2713,FD2713
162,163,4.8.4FD2724,Peralatan Khusus,Gudang Prasarana Pekalongan,FD2724,FD2724

In [12]:
smn = smn[['No', 'no_identitas2','Jenis Sarana', 'Lokasi Penempatan']]

In [13]:
smn

      No no_identitas2      Jenis Sarana               Lokasi Penempatan
0      1     CC3001201         Lokomotif                  PT INKA Madiun
1      2     CC3001202         Lokomotif        Workshop Balai Perawatan
2      3     CC3001203         Lokomotif       Depo Lokomotif Tanahabang
3      4     CC3001401         Lokomotif                  Sumatera Utara
4      5     CC3001402         Lokomotif                         Lampung
..   ...           ...               ...                             ...
158  159        V2R510  Peralatan Khusus        Workshop Balai Perawatan
159  160        FD2124  Peralatan Khusus     Gudang Prasarana Jatibarang
160  161        FD2728  Peralatan Khusus  Gudang Prasarana Parungpanjang
161  162        FD2713  Peralatan Khusus         Gudang Prasarana Bangil
162  163        FD2724  Peralatan Khusus     Gudang Prasarana Pekalongan

[163 rows x 4 columns]

In [14]:
smn['Lokasi Penempatan'].value_counts(dropna = False)

Gudang Peti Kemas Gedebage        53
Depo Kereta Cipinang              22
Workshop Balai Perawatan          17
Sumatera Utara                    12
Gudang Prasarana Kroya            10
Gudang Prasarana Pekalongan        9
Sulawesi Selatan                   8
Lampung                            5
Gudang Prasarana Jatibarang        5
Bandung                            3
Solo                               3
Sumatera Selatan                   2
Depo Lokomotif Tanahabang          2
BTP Wil. Sumut                     1
LRT Palembang                      1
BTP Wil. Jateng                    1
BTP Wil. Jabar                     1
Depok                              1
PT INKA Madiun                     1
Gudang Prasarana Parungpanjang     1
Gudang Prasarana Bangil            1
Depo Cipinang                      1
BTP Wil. Sumsel                    1
Gudang Prasarana Payakabung        1
BTP Wil. Jatim                     1
Name: Lokasi Penempatan, dtype: int64

In [15]:
import re
def daop(col) :
    if col['Lokasi Penempatan'] == "Gudang Peti Kemas Gedebage" or col['Lokasi Penempatan'] == "Gudang Prasarana Jatibarang" or col['Lokasi Penempatan'] == "Bandung":
        daop = 'BTP Wil. Jabar'
    elif col['Lokasi Penempatan'] == "Gudang Prasarana Pekalongan" or col['Lokasi Penempatan'] == "Gudang Prasarana Kroya" or col['Lokasi Penempatan'] == "Solo":
        daop = 'BTP Wil. Jateng'
    elif col['Lokasi Penempatan'] == "Gudang Prasarana Bangil" or col['Lokasi Penempatan'] == "PT INKA Madiun" :
        daop = 'BTP Wil. Jatim'
    elif col['Lokasi Penempatan'] == "Gudang Prasarana Parungpanjang" or col['Lokasi Penempatan'] == "Depo Lokomotif Tanahabang" or col['Lokasi Penempatan'] == "Depok" :
        daop = 'BTP Wil. JakBan'
    elif col['Lokasi Penempatan'] == "Depo Cipinang" or col['Lokasi Penempatan'] == "Depo Kereta Cipinang" :
        daop = 'BTP Wil. JakBan'
    elif col['Lokasi Penempatan'] == "Sumatera Utara" :
        daop = 'BTP Wil. Sumut'
    elif col['Lokasi Penempatan'] == "Sumatera Selatan" or col['Lokasi Penempatan'] == "Gudang Prasarana Payakabung" or col['Lokasi Penempatan'] == "Lampung":
        daop = 'BTP Wil. Sumsel'
    elif col['Lokasi Penempatan'] == "Sulawesi Selatan" :
        daop = 'BTP Wil. Sulsel'
    else :
        daop = 'Workshop Balai Perawatan'
        
    return  daop

In [16]:
smn['daop'] = smn.apply(daop, axis=1)

In [17]:
smn['daop'].value_counts(dropna = False)

BTP Wil. Jabar              61
BTP Wil. JakBan             27
Workshop Balai Perawatan    23
BTP Wil. Jateng             22
BTP Wil. Sumut              12
BTP Wil. Sulsel              8
BTP Wil. Sumsel              8
BTP Wil. Jatim               2
Name: daop, dtype: int64

In [18]:
smn['daop'] = smn['daop'].str.replace('BTP Wil. ', 'BTP ')

<ipython-input-18-7cfce76d328a>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  smn['daop'] = smn['daop'].str.replace('BTP Wil. ', 'BTP ')

In [19]:
smn.head()

,No,no_identitas2,Jenis Sarana,Lokasi Penempatan,daop
0,1,CC3001201,Lokomotif,PT INKA Madiun,BTP Jatim
1,2,CC3001202,Lokomotif,Workshop Balai Perawatan,Workshop Balai Perawatan
2,3,CC3001203,Lokomotif,Depo Lokomotif Tanahabang,BTP JakBan
3,4,CC3001401,Lokomotif,Sumatera Utara,BTP Sumut
4,5,CC3001402,Lokomotif,Lampung,BTP Sumsel

In [20]:
smn['daop'] = smn['daop'].str.replace('Workshop Balai Perawatan', 'BALAI PERAWATAN')

In [21]:
smn.head()

   No no_identitas2 Jenis Sarana          Lokasi Penempatan             daop
0   1     CC3001201    Lokomotif             PT INKA Madiun        BTP Jatim
1   2     CC3001202    Lokomotif   Workshop Balai Perawatan  BALAI PERAWATAN
2   3     CC3001203    Lokomotif  Depo Lokomotif Tanahabang       BTP JakBan
3   4     CC3001401    Lokomotif             Sumatera Utara        BTP Sumut
4   5     CC3001402    Lokomotif                    Lampung       BTP Sumsel

In [24]:
colnames=['kode_daop', 'nama_daop', 'created_at', 'update_at']
daop = pd.read_csv('tbldaops_updatebtp.csv', sep=',' , names=colnames)
daop

,kode_daop,nama_daop,created_at,update_at
0,7,DAOP 1 JAKARTA,NaN,NaN
1,8,DAOP 2 BANDUNG,NaN,NaN
2,9,DAOP 3 CIREBON,NaN,NaN
3,10,DAOP 4 SEMARANG,NaN,NaN
4,11,DAOP 5 PURWOKERTO,NaN,NaN
5,12,DAOP 6 YOGYAKARTA,NaN,NaN
6,13,DAOP 7 MADIUN,NaN,NaN
7,14,DAOP 8 SURABAYA,NaN,NaN
8,15,DAOP 9 JEMBER,NaN,NaN
9,16,DIVRE I SUMATERA UTARA,NaN,NaN
10,17,DIVRE II SUMATERA BARAT,NaN,NaN
11,18,DIVRE III SUMATERA SELATAN,NaN,NaN
12,24,PT KAI COMMUTER JABOTABEK,NaN,NaN
13,25,BALAI PERAWATAN,NaN,NaN
14,26,DIVRE IV LAMPUNG,2020-07-23 02:57:57,2020-07-23 02:57:57
15,27,PROV DKI JAKARTA,2020-07-23 02:59:12,2020-07-23 02:59:12
16,28,BTP JakBan,2021-07-09 02:03:45,2021-07-09 02:03:45
17,29,BTP Jabar,2021-07-09 02:03:54,2021-07-09 02:03:54
18,30,BTP Jateng,2021-07-09 02:04:01,2021-07-09 02:04:01
19,31,BTP Jatim,2021-07-09 02:04:15,2021-07-09 02:04:15
20,32,BTP Sumut,2021-07-09 02:04:42,2021-07-09 02:04:42
21,33,BTP Sumbar,2021-07-09 02:04:52,2021-07-09 02:04:52
22,34,BTP Sumsel,2021-07-09 02:05:00,2021-07-09 02:05:00
23,35,BTP Sulsel,2021-07-09 02:05:41,2021-07-09 02:05:41

In [25]:
daop = daop[['nama_daop', 'kode_daop']]

In [26]:
smn_merge = pd.merge(smn, daop, how="left", left_on='daop', right_on = 'nama_daop')

In [27]:
smn_merge

,No,no_identitas2,Jenis Sarana,Lokasi Penempatan,daop,nama_daop,kode_daop
0,1,CC3001201,Lokomotif,PT INKA Madiun,BTP Jatim,BTP Jatim,31
1,2,CC3001202,Lokomotif,Workshop Balai Perawatan,BALAI PERAWATAN,BALAI PERAWATAN,25
2,3,CC3001203,Lokomotif,Depo Lokomotif Tanahabang,BTP JakBan,BTP JakBan,28
3,4,CC3001401,Lokomotif,Sumatera Utara,BTP Sumut,BTP Sumut,32
4,5,CC3001402,Lokomotif,Lampung,BTP Sumsel,BTP Sumsel,34
...,...,...,...,...,...,...,...
158,159,V2R510,Peralatan Khusus,Workshop Balai Perawatan,BALAI PERAWATAN,BALAI PERAWATAN,25
159,160,FD2124,Peralatan Khusus,Gudang Prasarana Jatibarang,BTP Jabar,BTP Jabar,29
160,161,FD2728,Peralatan Khusus,Gudang Prasarana Parungpanjang,BTP JakBan,BTP JakBan,28
161,162,FD2713,Peralatan Khusus,Gudang Prasarana Bangil,BTP Jatim,BTP Jatim,31
162,163,FD2724,Peralatan Khusus,Gudang Prasarana Pekalongan,BTP Jateng,BTP Jateng,30

In [29]:
smn_merge['kode_daop'].value_counts(dropna=False)

29    61
28    27
25    23
30    22
32    12
34     8
35     8
31     2
Name: kode_daop, dtype: int64

In [30]:
smn_merge.to_csv('smn_after.csv', sep=';')